### ISSUE TITLE
How to disable hassio_observer?

### ISSUE THREAD

**Issue by lovelylain** [home-assistant/plugin-observer#19]
It's useless for me, but it takes up too much memory. My device has just experienced a run out of memory and I suspect it has something to do with plugin-observer.
```
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  177   173 root     S     695m  40%   1   0% observer
  201     0 root     S     2600   0%   1   0% bash
  206   201 root     R     1636   0%   3   0% top
    1     0 root     S      192   0%   3   0% s6-svscan -t0 /var/run/s6/services
   31     1 root     S      192   0%   0   0% s6-supervise s6-fdholderd
  173     1 root     S      192   0%   1   0% s6-supervise observer
```
```
# docker images
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
homeassistant/qemuarm-64-homeassistant    0.118.1             c4953f3cb5e5        5 days ago          1.14GB
hassioaddons/node-red-aarch64             7.2.10              4fe2d0edbbd1        7 days ago          252MB
hassioaddons/adguard-aarch64              2.6.1               fee7e04d39e5        13 days ago         47.1MB
hassioaddons/nginxproxymanager-aarch64    0.8.2               a8c81417dee2        2 weeks ago         401MB
dwelch2101/zigbee2mqtt-aarch64            1.16.1              637938b4fb29        2 weeks ago         456MB
homeassistant/aarch64-hassio-supervisor   2020.11.0           d933ed23bed8        3 weeks ago         317MB
homeassistant/aarch64-hassio-dns          2020.11.0           af5ecb447947        3 weeks ago         130MB
homeassistant/aarch64-hassio-cli          2020.10.1           0f05fe76c14f        4 weeks ago         98.5MB
homeassistant/aarch64-hassio-observer     2020.10.1           2276cf8c8343        6 weeks ago         98.1MB
hassioaddons/phpmyadmin-aarch64           0.1.4               8f206347de6a        3 months ago        123MB
homeassistant/aarch64-hassio-multicast    3                   272cc794b62f        3 months ago        88.3MB
homeassistant/aarch64-hassio-audio        17                  7fa0e2cc52fe        3 months ago        110MB
portainer/portainer                       latest              1fdf590d1a36        4 months ago        68.5MB
homeassistant/aarch64-addon-mariadb       2.2.1               da3a7e5f170c        4 months ago        297MB
homeassistant/aarch64-addon-mosquitto     5.1                 56b6964bab3a        14 months ago       37.2MB
```
```
20-11-25 19:02:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
20-11-25 19:04:05 WARNING (MainThread) [supervisor.misc.tasks] Watchdog/Application found a problem with observer plugin!
20-11-25 19:04:27 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping hassio_observer application

20-11-25 19:07:54 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning hassio_observer application
20-11-25 19:09:07 INFO (MainThread) [supervisor.plugins.observer] Starting observer plugin
20-11-25 19:11:00 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
20-11-25 19:11:30 WARNING (MainThread) [supervisor.updater] Can't fetch versions from https://version.home-assistant.io/stable.json: 

20-11-25 19:14:35 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-11-25 19:14:40 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository

20-11-25 19:28:32 ERROR (SyncWorker_4) [supervisor.docker] Dockerd connection issue for hassio_observer: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=900)
20-11-25 19:29:51 ERROR (MainThread) [supervisor.plugins.observer] Can't start observer plugin
20-11-25 19:30:16 ERROR (MainThread) [supervisor.misc.tasks] Observer watchdog reanimation failed!
20-11-25 19:31:39 ERROR (MainThread) [asyncio] Task exception was never retrieved

future: <Task finished name='Task-583242' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=DockerRequestError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 102, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=900)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/docker/interface.py", line 164, in _is_running
    docker_container = self.sys_docker.containers.get(self.name)
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 887, in get
    resp = self.client.api.inspect_container(container_id)
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 771, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 228, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=900)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 339, in _watchdog_observer_docker
    await self.sys_plugins.observer.is_running()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/interface.py", line 170, in _is_running
    raise DockerRequestError() from err
supervisor.exceptions.DockerRequestError
20-11-25 19:36:52 WARNING (MainThread) [supervisor.misc.tasks] Watchdog/Application found a problem with observer plugin!
```

**Comment by lovelylain** [comment]
It may be that the lack of memory is causing hassio_observer to be out of trouble, rather than that hassio_observer is causing it to run out of memory。
